# ⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛

# Developed by: ElitePusher#3574

# @UniteWarps | 2022

# ⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛

Messages:
  Prefix: ' &9UniteWarps &8▪ &7'
  NoPermission: ' &9UniteWarps &8▪ &cYou do not have access to this command!'
Version:
  Version: 1.0 #Don't change!